plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running

hostnames:
  - instance-id

keyed_groups:
  - prefix: env
    key: tags.Environment
  - prefix: role
    key: tags.Role
