---
- name: Atualizar cache de pacotes
  ansible.builtin.apt:
    update_cache: yes

- name: Instalar Certbot
  ansible.builtin.apt:
    name: certbot
    state: present

- name: Criar diretório certbot webroot
  ansible.builtin.file:
    path: /var/www/certbot
    state: directory
    mode: '0755'