name: Ansible CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ansible

jobs:
  ansible:
    name: Ansible Configuration (SSM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::340705986117:role/PlatformInfraGitHubRunnerAnsibleRole
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Install AWS dependencies and collection
        run: |
          pipx inject ansible-core boto3 botocore
          ansible-galaxy collection install amazon.aws community.aws --force

      - name: Install AWS Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Wait for EC2 instances to register in SSM
        run: |
          echo "Waiting for EC2 instances to become available in AWS SSM..."

          for i in {1..30}; do
            INSTANCE_COUNT=$(aws ssm describe-instance-information \
              --query "InstanceInformationList[*].InstanceId" \
              --output text | wc -w)

            if [ "$INSTANCE_COUNT" -gt 0 ]; then
              echo "EC2 instance registered in SSM."
              exit 0
            fi

            echo "Still waiting for SSM registration..."
            sleep 10
          done

          echo "Timeout waiting for EC2 instances in SSM."
          exit 1

      - name: Validate inventory
        run: ansible-inventory -i inventories/aws_ec2.yml --graph

      - name: Run Ansible Playbook via SSM
        run: ansible-playbook -i inventories/aws_ec2.yml playbooks/setup_docker.yml -vv